export const CREATE_BOOKING = 'CREATE_BOOKING';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const GET_BOOKING_BY_ID = 'GET_BOOKING_BY_ID';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
