// Package create  constants
export const CREATE_PACKAGE_REQUEST = 'CREATE_PACKAGE_REQUEST';
export const CREATE_PACKAGE_SUCCESS = 'CREATE_PACKAGE_SUCCESS';
export const CREATE_PACKAGE_FAILURE = 'CREATE_PACKAGE_FAILURE';

// Package get pacnstants
export const GET_ALL_PACKAGES_REQUEST = 'GET_ALL_PACKAGES_REQUEST';
export const GET_ALL_PACKAGES_SUCCESS = 'GET_ALL_PACKAGES_SUCCESS';
export const GET_ALL_PACKAGES_FAILURE = 'GET_ALL_PACKAGES_FAILURE';

// Package get by age constants
export const GET_PACKAGE_BY_ID_REQUEST = 'GET_PACKAGE_BY_ID_REQUEST';
export const GET_PACKAGE_BY_ID_SUCCESS = 'GET_PACKAGE_BY_ID_SUCCESS';
export const GET_PACKAGE_BY_ID_FAILURE = 'GET_PACKAGE_BY_ID_FAILURE';

// Package update  constants
export const UPDATE_PACKAGE_REQUEST = 'UPDATE_PACKAGE_REQUEST';
export const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS';
export const UPDATE_PACKAGE_FAILURE = 'UPDATE_PACKAGE_FAILURE';

// Package delete  constants
export const DELETE_PACKAGE_REQUEST = 'DELETE_PACKAGE_REQUEST';
export const DELETE_PACKAGE_SUCCESS = 'DELETE_PACKAGE_SUCCESS';
export const DELETE_PACKAGE_FAILURE = 'DELETE_PACKAGE_FAILURE';