// sparepartsConstants.jsx

export const SPAREPARTS_LIST_REQUEST = 'SPAREPARTS_LIST_REQUEST';
export const SPAREPARTS_LIST_SUCCESS = 'SPAREPARTS_LIST_SUCCESS';
export const SPAREPARTS_LIST_FAIL = 'SPAREPARTS_LIST_FAIL';

export const SPAREPARTS_DETAILS_REQUEST = 'SPAREPARTS_DETAILS_REQUEST';
export const SPAREPARTS_DETAILS_SUCCESS = 'SPAREPARTS_DETAILS_SUCCESS';
export const SPAREPARTS_DETAILS_FAIL = 'SPAREPARTS_DETAILS_FAIL';

export const SPAREPARTS_CREATE_REQUEST = 'SPAREPARTS_CREATE_REQUEST';
export const SPAREPARTS_CREATE_SUCCESS = 'SPAREPARTS_CREATE_SUCCESS';
export const SPAREPARTS_CREATE_FAIL = 'SPAREPARTS_CREATE_FAIL';

export const SPAREPARTS_UPDATE_REQUEST = 'SPAREPARTS_UPDATE_REQUEST';
export const SPAREPARTS_UPDATE_SUCCESS = 'SPAREPARTS_UPDATE_SUCCESS';
export const SPAREPARTS_UPDATE_FAIL = 'SPAREPARTS_UPDATE_FAIL';

export const SPAREPARTS_DELETE_REQUEST = 'SPAREPARTS_DELETE_REQUEST';
export const SPAREPARTS_DELETE_SUCCESS = 'SPAREPARTS_DELETE_SUCCESS';
export const SPAREPARTS_DELETE_FAIL = 'SPAREPARTS_DELETE_FAIL';
